### ISSUE TITLE
Doesn't take into account previous tweets

### ISSUE THREAD

**Issue by raveeshbhalla** [frag-o-matic/TheLalaList#4]
Referencing the Uncommon tweet: https://github.com/frag-o-matic/TheLalaList/blob/master/README.md#uncommonis

The suggestion for not interviewing people who cannot join over the next month comes after the [recommendation to shorten the notice period across the board](https://twitter.com/raveeshbhalla/status/973468070436941824). This is a core issue that I've been railing against in public and private for a while, not simply because long notice periods leads to future employees backing out but just because it's just good practice.

**Comment by frag-o-matic** [comment]
Corrected in 86d71554888026e66d50d3a1050b486bfbf562d5
